language: java

sudo: false

addons:
  hosts:
    - mysql

services:
  - docker

cache:
  directories:
    - ./target

jobs:
  include:
    - stage: build and package
      install: skip
      jdk: oraclejdk11
      script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V mvn compile -DskipTests=true  && mvn package -DskipTests=true
    - stage: unit tests
      install: skip
      jdk: oraclejdk11
      script: mvn test -Dtest=com.napier.sem.LanguageReportTest
    - stage: integration tests
      jdk: oraclejdk11
      script: docker-compose run integration_tests
    - stage: deploy
      install: skip
      jdk: oraclejdk11
      script: echo "Deploy"