language: java

sudo: false

addons:
  hosts:
    - mysql

services:
  - docker

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  - mvn clean

jobs:
  include:
    - stage: unit tests
      install: skip
      jdk: oraclejdk11
      script: mvn test -Dtest=com.napier.sem.LanguageReportTest,com.napier.sem.CountryReportTest,com.napier.sem.CityReportTest
    - stage: integration tests
      jdk: oraclejdk11
      script: docker-compose run integration_tests
    - stage: GitHub Release
      # We don't want to install
      install: skip
      # We will build the JAR
      jdk: oraclejdk11
      script:
      - echo "Deploying to GitHub Releases"
      # Package (build) the JAR
      - mvn package -DskipTests=true -Dmaven.javadoc.skip=true
      before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "Marx1211"
      - git config --local user.email "mdfp1211@gmail.com"
      # Create temporary tag from date and Git log.
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d')-$(git log --format=%h -1)}
      # Set tag
      - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        # This is the token we set before
        api_key: $GITHUB_OAUTH_TOKEN
        # Copy built JAR file to release.  JAR built in $TRAVIS_BUILD_DIR/target
        file: $TRAVIS_BUILD_DIR/target/seMethods.jar
        skip_cleanup: true