sudo: required
language: java
services:
- docker
after_success:
- docker-compose up --abort-on-container-exit
before_install:
- openssl aes-256-cbc -K $encrypted_f7e1ca0be34e_key -iv $encrypted_f7e1ca0be34e_iv
  -in client-secret.json.enc -out client-secret.json -d
