version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306
      WAIT_HOSTS_TIMEOUT: 120
      WAIT_SLEEP_INTERVAL: 5
  # db is is db folder
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
