version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: ./docker/app
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
      WAIT_HOSTS_TIMEOUT: 120
      WAIT_SLEEP_INTERVAL: 5
  integration_tests:
    build: ./docker/test
    depends_on:
      - mysql
    volumes:
      - ./:/var/code
    environment:
      WAIT_HOSTS: mysql:3306
      WAIT_HOSTS_TIMEOUT: 120
      WAIT_SLEEP_INTERVAL: 5
  # db is is db folder
  mysql:
    build: ./docker/database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./docker/database/world.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: albert-sapo
    ports:
      - "3306:3306"
    expose:
      - "3306"

